# Generated by Django 2.2.28 on 2023-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employe_id', models.BigIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
    ]
